Update subtitle, audio, video and chapter menu lists
darsain/uosc pull request #98
Opened 2022-07-19 21:20 UTC by christoph-heinrich

The playlist menu list would reflect changes of the underlying data.
That now also happens for the menu lists of all three tracks as well as
chapters. Closes #21

2022-08-14 10:01 UTC, tomasklaen commented
Apart of the nitpicks in the review it looks good 👍.

2022-08-14 12:31 UTC, christoph-heinrich commented
I would like to address those nitpicks, but unfortunately there is no review...

2022-08-14 13:03 UTC, tomasklaen requested changes

2022-08-15 00:24 UTC, christoph-heinrich commented on uosc.lua
> +function create_self_updating_menu_opener(menu_title, menu_type, list_props, active_props,
I don't remember what use case I had in mind to make them arrays.
They are now simple values in the table.

2022-08-15 07:20 UTC, tomasklaen approved these changes

2022-08-15 07:20 UTC, merged